apiVersion: v1
kind: Service 
metadata:
  name: voting-service-app
  labels:
    name: voting-service-app
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
     labels:
        name: voting-app-pod
        app: demo-voting-app